# Generated by Django 4.2.2 on 2023-07-15 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='pagina_web',
        ),
    ]
